### PR TITLE
Fix build errors on Alpine (musl libc)

### LINKED ISSUE #15: v0.9.0+ fails to build on Alpine/musl libc
```
# (cd _build/default/src && /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlc.opt -g -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/base -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/core -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/core_kernel -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/jane-street-headers -ccopt -g -o extended_unix_stubs.o extended_unix_stubs.c)
# extended_unix_stubs.c: In function 'quota_query':
# extended_unix_stubs.c:126:38: error: 'BLOCK_SIZE' undeclared (first use in this function)
#  #  define QUOTA_BYTES_PER_SPACE_UNIT BLOCK_SIZE
#                                       ^
# extended_unix_stubs.c:159:16: note: in expansion of macro 'QUOTA_BYTES_PER_SPACE_UNIT'
#    bytes_used = QUOTA_BYTES_PER_SPACE_UNIT * (int64_t) QUOTA_SPACE_USED(quota);
#                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
# extended_unix_stubs.c:126:38: note: each undeclared identifier is reported only once for each function it appears in
#  #  define QUOTA_BYTES_PER_SPACE_UNIT BLOCK_SIZE
#                                       ^
# extended_unix_stubs.c:159:16: note: in expansion of macro 'QUOTA_BYTES_PER_SPACE_UNIT'
#    bytes_used = QUOTA_BYTES_PER_SPACE_UNIT * (int64_t) QUOTA_SPACE_USED(quota);
#                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
# extended_unix_stubs.c: In function 'quota_modify':
# extended_unix_stubs.c:126:38: error: 'BLOCK_SIZE' undeclared (first use in this function)
#  #  define QUOTA_BYTES_PER_SPACE_UNIT BLOCK_SIZE
#                                       ^
# extended_unix_stubs.c:194:63: note: in expansion of macro 'QUOTA_BYTES_PER_SPACE_UNIT'
#    quota.dqb_bsoftlimit = Int63_val(Field(v_bytes_limit, 0)) / QUOTA_BYTES_PER_SPACE_UNIT;
#                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~

```

This in turns breaks a lot of container builds as they tend to use Alpine.

example build log https://ci.ocaml.io/log/saved/docker-build-a58cd3ed12b1742875644e71f82d488b/8279d0f707cacc8a751302420a5e5ddb10849844

### PR DESCRIPTION
**Pull request by teohhanhui**
Fixes #15

Replaces #17

### CODE REVIEW

**Comment by junlong-gao** [comment]
Hi, 

What is the progress of this PR? We currently see the same build errors (https://github.com/janestreet/core_extended/issues/15) for core_extended when using opam in alpine container.

Thanks!

**Comment by yminsky** [comment]
We're in the process of putting out a new stable release of our packages where this is no longer an issue. We broke up Core_extended into a bunch of smaller libraries, and rereleased those that seemed useful. The functionality modified in this PR moved into Unix_extended, which we did not release, so I think maybe this issue is no longer relevant? If someone needs Unix_extended, we can release it as well, but I don't think there's really any call for it.

**Comment by junlong-gao** [comment]
Hi @yminsky,

Thanks for your clarification and the continued support for JS high-quality OCaml libraries!

We have worked around some use cases so Core_extended in alpine is no longer a blocker for us (even though it would be nice to have the components in the new releases. Having a statically linked OCaml binary enables many interesting use cases due to our special OS environment).

**Comment by yminsky** [comment]
Sorry, but when you say it would be nice to "have the components" in the new releases, do you mean, the components of Core_extended generally, or the unix-bits that are referenced by this CR specifically? A bunch of the components of Core_extended are still in the public release. If there's a specific thing you're using that you'd like to be included, it would be good to know what...

**Comment by jeremiedimino** [comment]
cf https://github.com/janestreet/core_extended/issues/15#issuecomment-696030767

**Pull request closed without merging**
